/**
 * Enumerations for DataVector. Defined in the global namespace so the enums 
 * names can be shorter (i.e. w/o namespace) throughout configs and flight 
 * software.
 */

#ifndef DATA_VECTOR_ENUMS_HPP
#define DATA_VECTOR_ENUMS_HPP

#include <stdint.h>

/**
 * Data Vector element type enumeration.
 */
enum DataVectorElementType_t : uint8_t
{
    DV_T_UINT8,
    DV_T_UINT16,
    DV_T_UINT32,
    DV_T_UINT64,
    DV_T_INT8,
    DV_T_INT16,
    DV_T_INT32,
    DV_T_INT64,
    DV_T_FLOAT,
    DV_T_DOUBLE,
    DV_T_BOOL,

    DV_T_LAST
};

/**
 * Possible regions in Data Vector.
 */
enum DataVectorRegion_t : uint32_t
{

///////////////////////////////// TEST REGIONS /////////////////////////////////

    /* Test Regions */
    DV_REG_TEST0,
    DV_REG_TEST1,
    DV_REG_TEST2,

///////////////////////////////// FSW REGIONS //////////////////////////////////

    DV_REG_CN,
    DV_REG_DN0_TO_CN,
    DV_REG_DN1_TO_CN,
    DV_REG_DN2_TO_CN,
    DV_REG_GROUND_TO_CN,
    DV_REG_CN_TO_DN0,
    DV_REG_CN_TO_DN1,
    DV_REG_CN_TO_DN2,

    DV_REG_LAST
};

/**
 * Possible elements in Data Vector.
 */
enum DataVectorElement_t : uint32_t
{

///////////////////////////////// TEST ELEMENTS ////////////////////////////////

    /* Generic Test Elements */
    DV_ELEM_TEST0,
    DV_ELEM_TEST1,
    DV_ELEM_TEST2,
    DV_ELEM_TEST3,
    DV_ELEM_TEST4,
    DV_ELEM_TEST5,
    DV_ELEM_TEST6,
    DV_ELEM_TEST7,
    DV_ELEM_TEST8,
    DV_ELEM_TEST9,
    DV_ELEM_TEST10,
    DV_ELEM_TEST11,
    DV_ELEM_TEST12,
    DV_ELEM_TEST13,
    DV_ELEM_TEST14,
    DV_ELEM_TEST15,
    DV_ELEM_TEST16,
    DV_ELEM_TEST17,
    DV_ELEM_TEST18,
    DV_ELEM_TEST19,
    DV_ELEM_TEST20,
    DV_ELEM_TEST21,
    DV_ELEM_TEST22,
    DV_ELEM_TEST23,
    DV_ELEM_TEST24,
    DV_ELEM_TEST25,
    DV_ELEM_TEST26,
    DV_ELEM_TEST27,
    DV_ELEM_TEST28,
    DV_ELEM_TEST29,
    DV_ELEM_TEST30,
    DV_ELEM_TEST31,
    DV_ELEM_TEST32,
    DV_ELEM_TEST33,
    DV_ELEM_TEST34,
    DV_ELEM_TEST35,
    DV_ELEM_TEST36,
    DV_ELEM_TEST37,
    DV_ELEM_TEST38,
    DV_ELEM_TEST39,
    DV_ELEM_TEST40,
    DV_ELEM_TEST41,
    DV_ELEM_TEST42,
    DV_ELEM_TEST43,
    DV_ELEM_TEST44,
    DV_ELEM_TEST45,
    DV_ELEM_TEST46,
    DV_ELEM_TEST47,
    DV_ELEM_TEST48,
    DV_ELEM_TEST49,
    DV_ELEM_TEST50,
    DV_ELEM_TEST51,
    DV_ELEM_TEST52,
    DV_ELEM_TEST53,
    DV_ELEM_TEST54,
    DV_ELEM_TEST55,
    DV_ELEM_TEST56,
    DV_ELEM_TEST57,
    DV_ELEM_TEST58,
    DV_ELEM_TEST59,
    DV_ELEM_TEST60,
    DV_ELEM_TEST61,
    DV_ELEM_TEST62,
    DV_ELEM_TEST63,
    DV_ELEM_TEST64,
    DV_ELEM_TEST65,
    DV_ELEM_TEST66,
    DV_ELEM_TEST67,
    DV_ELEM_TEST68,
    DV_ELEM_TEST69,
    DV_ELEM_TEST70,
    DV_ELEM_TEST71,
    DV_ELEM_TEST72,
    DV_ELEM_TEST73,
    DV_ELEM_TEST74,
    DV_ELEM_TEST75,
    DV_ELEM_TEST76,
    DV_ELEM_TEST77,
    DV_ELEM_TEST78,
    DV_ELEM_TEST79,
    DV_ELEM_TEST80,
    DV_ELEM_TEST81,
    DV_ELEM_TEST82,
    DV_ELEM_TEST83,
    DV_ELEM_TEST84,
    DV_ELEM_TEST85,
    DV_ELEM_TEST86,
    DV_ELEM_TEST87,
    DV_ELEM_TEST88,
    DV_ELEM_TEST89,
    DV_ELEM_TEST90,
    DV_ELEM_TEST91,
    DV_ELEM_TEST92,
    DV_ELEM_TEST93,
    DV_ELEM_TEST94,
    DV_ELEM_TEST95,
    DV_ELEM_TEST96,
    DV_ELEM_TEST97,
    DV_ELEM_TEST98,
    DV_ELEM_TEST99,
    DV_ELEM_TEST100,
    DV_ELEM_TEST101,
    DV_ELEM_TEST102,
    DV_ELEM_TEST103,
    DV_ELEM_TEST104,
    DV_ELEM_TEST105,
    DV_ELEM_TEST106,
    DV_ELEM_TEST107,
    DV_ELEM_TEST108,
    DV_ELEM_TEST109,
    DV_ELEM_TEST110,
    DV_ELEM_TEST111,
    DV_ELEM_TEST112,
    DV_ELEM_TEST113,
    DV_ELEM_TEST114,
    DV_ELEM_TEST115,
    DV_ELEM_TEST116,
    DV_ELEM_TEST117,
    DV_ELEM_TEST118,
    DV_ELEM_TEST119,
    DV_ELEM_TEST120,
    DV_ELEM_TEST121,
    DV_ELEM_TEST122,
    DV_ELEM_TEST123,
    DV_ELEM_TEST124,
    DV_ELEM_TEST125,
    DV_ELEM_TEST126,
    DV_ELEM_TEST127,
    DV_ELEM_TEST128,

    /* Test Controllers */
    DV_ELEM_TEST_CONTROLLER_MODE,
    DV_ELEM_DN_RESP_CTRL_MODE,
    DV_ELEM_ERROR_CTRL_MODE,
    DV_ELEM_MISS_CTRL_MODE,
    DV_ELEM_THREAD_KILL_CTRL_MODE,
    DV_ELEM_DEVICE_NODE_CTRL_MODE,

    /* RCS Controller */
    DV_ELEM_RCS_CONTROLLER_MODE,

    /* LED Controller */
    DV_ELEM_LED_CONTROLLER_MODE,
    DV_ELEM_LED_CONTROL_VAL,
    DV_ELEM_LED_FEEDBACK_VAL,

    /* Recovery Igniter Test Script */
    DV_ELEM_RECIGNTEST_CONTROL_VAL,
    DV_ELEM_RECIGNTEST_FEEDBACK_VAL,

///////////////////////////////// FSW ELEMENTS /////////////////////////////////

    /* Health Counters */
    DV_ELEM_CN_LOOP_DEADLINE_MISSES,
    DV_ELEM_CN_COMMS_DEADLINE_MISSES,
    DV_ELEM_CN_LOOP_COUNT,
    DV_ELEM_CN_ERROR_COUNT,
    DV_ELEM_CN_MSG_TX_COUNT,
    DV_ELEM_CN_MSG_RX_COUNT,
    DV_ELEM_DN0_LOOP_COUNT,
    DV_ELEM_DN0_ERROR_COUNT,
    DV_ELEM_DN0_MSG_TX_COUNT,
    DV_ELEM_DN0_MSG_RX_COUNT,
    DV_ELEM_DN1_LOOP_COUNT,
    DV_ELEM_DN1_ERROR_COUNT,
    DV_ELEM_DN1_MSG_TX_COUNT,
    DV_ELEM_DN1_MSG_RX_COUNT,
    DV_ELEM_DN2_LOOP_COUNT,
    DV_ELEM_DN2_ERROR_COUNT,
    DV_ELEM_DN2_MSG_TX_COUNT,
    DV_ELEM_DN2_MSG_RX_COUNT,
    DV_ELEM_GROUND_MSG_TX_COUNT,
    DV_ELEM_GROUND_MSG_RX_COUNT,
    DV_ELEM_DN0_RX_MISS_COUNT,
    DV_ELEM_DN1_RX_MISS_COUNT,
    DV_ELEM_DN2_RX_MISS_COUNT,

    /* Time */
    DV_ELEM_CN_TIME_NS,

    /* State Machine */
    DV_ELEM_STATE,

    /* Command Handler */
    DV_ELEM_CMD_REQ,
    DV_ELEM_CMD,
    DV_ELEM_CMD_WRITE_ELEM,
    DV_ELEM_CMD_WRITE_VAL,
    DV_ELEM_LAST_CMD_REQ_NUM,
    DV_ELEM_LAST_CMD_PROC_NUM,

    DV_ELEM_LAST
};

#endif
