/**
 * See ProfilePlatform_Config.hpp for instructions on running test.
 */

#include "ProfilePlatform_Config.hpp"

/*************************** DATA VECTOR CONFIGS ******************************/

DataVector::RegionConfig_t ProfilePlatform_Config::mDvRegCnToDn0 =
{
    DV_REG_CN_TO_DN0,
    // TYPE           ELEM                                  INITIAL_VAL  
    {DV_ADD_UINT8   ( DV_ELEM_RXN_TIME_DN0_CTRL_MODE,       MODE_SAFED   ),
     DV_ADD_UINT8   ( DV_ELEM_OVERHEAD_DN0_CTRL_MODE,       MODE_SAFED   ),
     DV_ADD_UINT16  ( DV_ELEM_TEST0,                        0            ),
     DV_ADD_UINT32  ( DV_ELEM_TEST1,                        0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST2,                        0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST3,                        0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST4,                        0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST5,                        0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST6,                        0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST7,                        0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST8,                        0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST9,                        0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST10,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST11,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST12,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST13,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST14,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST15,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST16,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST17,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST18,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST19,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST20,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST21,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST22,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST23,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST24,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST25,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST26,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST27,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST28,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST29,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST30,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST31,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST32,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST33,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST34,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST35,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST36,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST37,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST38,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST39,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST40,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST41,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST42,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST43,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST44,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST45,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST46,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST47,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST48,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST49,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST50,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST51,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST52,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST53,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST54,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST55,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST56,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST57,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST58,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST59,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST60,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST61,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST62,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST63,                       0            ),
     // 512 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST64,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST65,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST66,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST67,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST68,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST69,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST70,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST71,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST72,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST73,                       0            ),
     // 600 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST74,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST75,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST76,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST77,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST78,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST79,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST80,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST81,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST82,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST83,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST84,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST85,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST86,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST87,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST88,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST89,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST90,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST91,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST92,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST93,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST94,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST95,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST96,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST97,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST98,                       0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST99,                       0            ),
     // 800 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST100,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST101,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST102,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST103,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST104,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST105,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST106,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST107,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST108,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST109,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST110,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST111,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST112,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST113,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST114,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST115,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST116,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST117,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST118,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST119,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST120,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST121,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST122,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST123,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST124,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST125,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST126,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST127,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST128,                      0            )},
};

DataVector::RegionConfig_t ProfilePlatform_Config::mDvRegCnToDn1 = 
{
    DV_REG_CN_TO_DN1,
    // TYPE          ELEM                                   INITIAL_VAL   
    {DV_ADD_UINT8   ( DV_ELEM_RXN_TIME_DN1_CTRL_MODE,       MODE_SAFED   ),
     DV_ADD_UINT8   ( DV_ELEM_OVERHEAD_DN1_CTRL_MODE,       MODE_SAFED   ),
     DV_ADD_UINT16  ( DV_ELEM_TEST129,                      0            ),
     DV_ADD_UINT32  ( DV_ELEM_TEST130,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST131,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST132,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST133,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST134,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST135,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST136,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST137,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST138,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST139,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST140,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST141,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST142,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST143,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST144,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST145,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST146,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST147,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST148,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST149,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST150,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST151,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST152,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST153,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST154,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST155,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST156,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST157,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST158,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST159,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST160,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST161,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST162,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST163,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST164,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST165,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST166,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST167,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST168,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST169,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST170,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST171,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST172,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST173,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST174,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST175,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST176,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST177,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST178,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST179,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST180,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST181,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST182,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST183,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST184,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST185,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST186,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST187,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST188,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST189,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST190,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST191,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST192,                      0            ),
     // 512 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST193,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST194,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST195,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST196,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST197,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST198,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST199,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST200,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST201,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST202,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST203,                      0            ),
     // 600 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST204,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST205,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST206,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST207,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST208,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST209,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST210,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST211,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST212,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST213,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST214,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST215,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST216,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST217,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST218,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST219,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST220,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST221,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST222,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST223,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST224,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST225,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST226,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST227,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST228,                      0            ),
     // 800 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST229,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST230,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST231,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST232,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST233,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST234,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST235,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST236,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST237,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST238,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST239,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST240,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST241,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST242,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST243,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST244,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST245,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST246,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST247,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST248,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST249,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST250,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST251,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST252,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST253,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST254,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST255,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST256,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST257,                      0            )}
};

DataVector::RegionConfig_t ProfilePlatform_Config::mDvRegCnToDn2 = 
{
    DV_REG_CN_TO_DN2,
    // TYPE          ELEM                                   INITIAL_VAL   
    {DV_ADD_UINT8   ( DV_ELEM_RXN_TIME_DN2_CTRL_MODE,       MODE_SAFED   ),
     DV_ADD_UINT8   ( DV_ELEM_OVERHEAD_DN2_CTRL_MODE,       MODE_SAFED   ),
     DV_ADD_UINT16  ( DV_ELEM_TEST258,                      0            ),
     DV_ADD_UINT32  ( DV_ELEM_TEST259,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST260,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST261,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST262,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST263,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST264,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST265,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST266,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST267,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST268,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST269,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST270,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST271,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST272,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST273,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST274,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST275,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST276,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST277,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST278,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST279,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST280,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST281,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST282,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST283,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST284,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST285,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST286,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST287,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST288,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST289,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST290,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST291,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST292,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST293,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST294,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST295,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST296,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST297,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST298,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST299,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST300,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST301,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST302,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST303,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST304,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST305,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST306,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST307,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST308,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST309,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST310,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST311,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST312,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST313,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST314,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST315,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST316,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST317,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST318,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST319,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST320,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST321,                      0            ),
     // 512 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST322,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST323,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST324,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST325,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST326,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST327,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST328,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST329,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST330,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST331,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST332,                      0            ),
     // 600 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST333,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST334,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST335,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST336,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST337,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST338,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST339,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST340,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST341,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST342,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST343,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST344,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST345,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST346,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST347,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST348,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST349,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST350,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST351,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST352,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST353,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST354,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST355,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST356,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST357,                      0            ),
     // 800 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST358,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST359,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST360,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST361,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST362,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST363,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST364,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST365,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST366,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST367,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST368,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST369,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST370,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST371,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST372,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST373,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST374,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST375,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST376,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST377,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST378,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST379,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST380,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST381,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST382,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST383,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST384,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST385,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST386,                      0            )}
};

DataVector::RegionConfig_t ProfilePlatform_Config::mDvRegDn0ToCn = 
{
    DV_REG_DN0_TO_CN,
    // TYPE          ELEM                                   INITIAL_VAL   
    {DV_ADD_UINT32  ( DV_ELEM_DN0_MSG_TX_COUNT,             0            ),
     DV_ADD_UINT32  ( DV_ELEM_DN0_MSG_RX_COUNT,             0            ),
     DV_ADD_UINT32  ( DV_ELEM_DN0_LOOP_COUNT,               0            ),
     DV_ADD_UINT32  ( DV_ELEM_DN0_ERROR_COUNT,              0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST387,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST388,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST389,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST390,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST391,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST392,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST393,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST394,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST395,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST396,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST397,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST398,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST399,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST400,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST401,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST402,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST403,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST404,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST405,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST406,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST407,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST408,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST409,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST410,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST411,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST412,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST413,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST414,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST415,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST416,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST417,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST418,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST419,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST420,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST421,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST422,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST423,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST424,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST425,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST426,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST427,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST428,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST429,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST430,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST431,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST432,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST433,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST434,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST435,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST436,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST437,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST438,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST439,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST440,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST441,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST442,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST443,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST444,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST445,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST446,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST447,                      0            ),
     // 512 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST448,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST449,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST450,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST451,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST452,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST453,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST454,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST455,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST456,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST457,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST458,                      0            ),
     // 600 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST459,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST460,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST461,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST462,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST463,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST464,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST465,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST466,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST467,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST468,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST469,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST470,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST471,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST472,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST473,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST474,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST475,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST476,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST477,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST478,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST479,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST480,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST481,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST482,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST483,                      0            ),
     // 800 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST484,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST485,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST486,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST487,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST488,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST489,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST490,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST491,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST492,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST493,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST494,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST495,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST496,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST497,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST498,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST499,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST500,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST501,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST502,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST503,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST504,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST505,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST506,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST507,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST508,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST509,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST510,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST511,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST512,                      0            )}
};

DataVector::RegionConfig_t ProfilePlatform_Config::mDvRegDn1ToCn = 
{
    DV_REG_DN1_TO_CN,
    // TYPE          ELEM                                   INITIAL_VAL   
    {DV_ADD_UINT32  ( DV_ELEM_DN1_MSG_TX_COUNT,             0            ),
     DV_ADD_UINT32  ( DV_ELEM_DN1_MSG_RX_COUNT,             0            ),
     DV_ADD_UINT32  ( DV_ELEM_DN1_LOOP_COUNT,               0            ),
     DV_ADD_UINT32  ( DV_ELEM_DN1_ERROR_COUNT,              0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST513,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST514,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST515,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST516,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST517,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST518,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST519,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST520,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST521,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST522,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST523,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST524,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST525,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST526,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST527,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST528,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST529,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST530,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST531,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST532,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST533,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST534,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST535,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST536,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST537,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST538,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST539,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST540,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST541,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST542,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST543,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST544,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST545,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST546,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST547,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST548,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST549,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST550,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST551,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST552,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST553,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST554,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST555,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST556,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST557,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST558,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST559,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST560,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST561,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST562,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST563,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST564,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST565,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST566,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST567,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST568,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST569,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST570,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST571,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST572,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST573,                      0            ),
     // 512 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST574,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST575,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST576,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST577,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST578,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST579,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST580,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST581,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST582,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST583,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST584,                      0            ),
     // 600 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST585,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST586,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST587,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST588,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST589,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST590,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST591,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST592,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST593,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST594,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST595,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST596,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST597,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST598,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST599,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST600,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST601,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST602,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST603,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST604,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST605,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST606,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST607,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST608,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST609,                      0            ),
     // 800 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST610,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST611,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST612,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST613,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST614,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST615,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST616,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST617,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST618,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST619,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST620,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST621,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST622,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST623,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST624,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST625,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST626,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST627,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST628,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST629,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST630,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST631,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST632,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST633,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST634,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST635,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST636,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST637,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST638,                      0            )}
};

DataVector::RegionConfig_t ProfilePlatform_Config::mDvRegDn2ToCn = 
{
    DV_REG_DN2_TO_CN,
    // TYPE          ELEM                                   INITIAL_VAL   
    {DV_ADD_UINT32  ( DV_ELEM_DN2_MSG_TX_COUNT,             0            ),
     DV_ADD_UINT32  ( DV_ELEM_DN2_MSG_RX_COUNT,             0            ),
     DV_ADD_UINT32  ( DV_ELEM_DN2_LOOP_COUNT,               0            ),
     DV_ADD_UINT32  ( DV_ELEM_DN2_ERROR_COUNT,              0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST639,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST640,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST641,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST642,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST643,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST644,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST645,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST646,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST647,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST648,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST649,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST650,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST651,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST652,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST653,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST654,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST655,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST656,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST657,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST658,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST659,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST660,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST661,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST662,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST663,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST664,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST665,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST666,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST667,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST668,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST669,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST670,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST671,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST672,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST673,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST674,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST675,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST676,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST677,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST678,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST679,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST680,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST681,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST682,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST683,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST684,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST685,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST686,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST687,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST688,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST689,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST690,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST691,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST692,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST693,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST694,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST695,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST696,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST697,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST698,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST699,                      0            ),
     // 512 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST700,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST701,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST702,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST703,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST704,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST705,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST706,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST707,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST708,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST709,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST710,                      0            ),
     // 600 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST711,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST712,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST713,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST714,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST715,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST716,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST717,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST718,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST719,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST720,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST721,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST722,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST723,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST724,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST725,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST726,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST727,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST728,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST729,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST730,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST731,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST732,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST733,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST734,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST735,                      0            ),
     // 800 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST736,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST737,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST738,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST739,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST740,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST741,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST742,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST743,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST744,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST745,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST746,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST747,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST748,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST749,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST750,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST751,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST752,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST753,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST754,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST755,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST756,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST757,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST758,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST759,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST760,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST761,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST762,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST763,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST764,                      0            )}
};

DataVector::RegionConfig_t ProfilePlatform_Config::mDvRegGndToCn =
{
    DV_REG_GROUND_TO_CN,
    // TYPE           ELEM                                  INITIAL_VAL  
    {DV_ADD_UINT8   ( DV_ELEM_CMD_REQ,                      CMD_NONE     ),
     DV_ADD_UINT32  ( DV_ELEM_LAST_CMD_REQ_NUM,             0            ),
     DV_ADD_UINT32  ( DV_ELEM_CMD_WRITE_ELEM,               DV_ELEM_LAST ),
     DV_ADD_UINT64  ( DV_ELEM_CMD_WRITE_VAL,                0            )}
};

DataVector::Config_t ProfilePlatform_Config::mCnDvConfig =
{
    {DV_REG_CN,
    // TYPE          ELEM                                   INITIAL_VAL
    {DV_ADD_UINT32  ( DV_ELEM_CN_LOOP_COUNT,                0            ),
     DV_ADD_UINT32  ( DV_ELEM_CN_ERROR_COUNT,               0            ),
     DV_ADD_UINT32  ( DV_ELEM_CN_MSG_TX_COUNT,              0            ),
     DV_ADD_UINT32  ( DV_ELEM_CN_MSG_RX_COUNT,              0            ),
     DV_ADD_UINT32  ( DV_ELEM_DN0_RX_MISS_COUNT,            0            ),
     DV_ADD_UINT32  ( DV_ELEM_DN1_RX_MISS_COUNT,            0            ),
     DV_ADD_UINT32  ( DV_ELEM_DN2_RX_MISS_COUNT,            0            ),
     DV_ADD_UINT32  ( DV_ELEM_CN_LOOP_DEADLINE_MISS_COUNT,  0            ),
     DV_ADD_UINT32  ( DV_ELEM_CN_COMMS_DEADLINE_MISS_COUNT, 0            ),
     DV_ADD_UINT8   ( DV_ELEM_CMD,                          CMD_NONE     ),
     DV_ADD_UINT32  ( DV_ELEM_LAST_CMD_PROC_NUM,            0            ),
     DV_ADD_UINT8   ( DV_ELEM_COMMS_CTRL_MODE,              MODE_SAFED   ),
     DV_ADD_UINT8   ( DV_ELEM_JITTER_CTRL_MODE,             MODE_SAFED   ),
     DV_ADD_UINT8   ( DV_ELEM_RXN_TIME_CN_CTRL_MODE,        MODE_SAFED   ),
     DV_ADD_UINT8   ( DV_ELEM_OVERHEAD_CN_CTRL_MODE,        MODE_SAFED   ),
     DV_ADD_UINT64  ( DV_ELEM_CN_TIME_NS,                   0            ),
     DV_ADD_UINT32  ( DV_ELEM_STATE,                        STATE_A      ),
     DV_ADD_UINT8   ( DV_ELEM_TEST765,                      0            ),
     DV_ADD_UINT16  ( DV_ELEM_TEST766,                      0            ),
     DV_ADD_UINT32  ( DV_ELEM_TEST767,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST768,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST769,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST770,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST771,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST772,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST773,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST774,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST775,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST776,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST777,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST778,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST779,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST780,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST781,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST782,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST783,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST784,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST785,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST786,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST787,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST788,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST789,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST790,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST791,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST792,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST793,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST794,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST795,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST796,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST797,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST798,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST799,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST800,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST801,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST802,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST803,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST804,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST805,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST806,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST807,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST808,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST809,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST810,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST811,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST812,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST813,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST814,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST815,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST816,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST817,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST818,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST819,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST820,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST821,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST822,                      0            ),
     // 512 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST823,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST824,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST825,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST826,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST827,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST828,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST829,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST830,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST831,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST832,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST833,                      0            ),
     // 600 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST834,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST835,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST836,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST837,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST838,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST839,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST840,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST841,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST842,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST843,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST844,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST845,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST846,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST847,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST848,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST849,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST850,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST851,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST852,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST853,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST854,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST855,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST856,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST857,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST858,                      0            ),
     // 800 bytes
     DV_ADD_UINT64  ( DV_ELEM_TEST859,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST860,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST861,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST862,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST863,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST864,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST865,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST866,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST867,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST868,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST869,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST870,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST871,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST872,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST873,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST874,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST875,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST876,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST877,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST878,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST879,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST880,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST881,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST882,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST883,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST884,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST885,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST886,                      0            ),
     DV_ADD_UINT64  ( DV_ELEM_TEST887,                      0            )}},

    ProfilePlatform_Config::mDvRegCnToDn0,
    ProfilePlatform_Config::mDvRegCnToDn1,
    ProfilePlatform_Config::mDvRegCnToDn2,
    ProfilePlatform_Config::mDvRegDn0ToCn,
    ProfilePlatform_Config::mDvRegDn1ToCn,
    ProfilePlatform_Config::mDvRegDn2ToCn,
    ProfilePlatform_Config::mDvRegGndToCn,
};

DataVector::Config_t ProfilePlatform_Config::mDnDvConfig =
{
#if DEVICE_NODE_TO_COMPILE == DEVICE_NODE0
    ProfilePlatform_Config::mDvRegCnToDn0,
    ProfilePlatform_Config::mDvRegDn0ToCn,
#elif DEVICE_NODE_TO_COMPILE == DEVICE_NODE1
    ProfilePlatform_Config::mDvRegCnToDn1,
    ProfilePlatform_Config::mDvRegDn1ToCn,
#else
    ProfilePlatform_Config::mDvRegCnToDn2,
    ProfilePlatform_Config::mDvRegDn2ToCn,
#endif
};

/************************* NETWORK MANAGER CONFIGS ****************************/

std::unordered_map<Node_t, 
                   NetworkManager::IP_t, 
                   EnumClassHash> ProfilePlatform_Config::mNodes = 
{
    {NODE_DEVICE0, DEVICE_NODE0_IP},
    {NODE_DEVICE1, DEVICE_NODE1_IP},
    {NODE_DEVICE2, DEVICE_NODE2_IP},
    {NODE_CONTROL, CONTROL_NODE_IP},
    {NODE_GROUND,  GROUND_NODE_IP}
};

std::vector<NetworkManager::ChannelConfig_t> 
    ProfilePlatform_Config::mChannels =
{
    {NODE_CONTROL, 
     NODE_DEVICE0, 
     static_cast<uint16_t> (NetworkManager::MIN_PORT)},
    {NODE_CONTROL,
     NODE_DEVICE1,
     static_cast<uint16_t> (NetworkManager::MIN_PORT + 1)},
    {NODE_CONTROL,
     NODE_DEVICE2,
     static_cast<uint16_t> (NetworkManager::MIN_PORT + 2)},
    {NODE_CONTROL,
     NODE_GROUND, 
     static_cast<uint16_t> (NetworkManager::MIN_PORT + 3)},
};

NetworkManager::Config_t ProfilePlatform_Config::mDnNmConfig =
{
    // Nodes
    ProfilePlatform_Config::mNodes,
    // Channels
    ProfilePlatform_Config::mChannels,
    // Me
    (Node_t) DEVICE_NODE_TO_COMPILE,
    // Msg Tx and Rx Counters.
#if DEVICE_NODE_TO_COMPILE == DEVICE_NODE0
    DV_ELEM_DN0_MSG_TX_COUNT,
    DV_ELEM_DN0_MSG_RX_COUNT,
#elif DEVICE_NODE_TO_COMPILE == DEVICE_NODE1
    DV_ELEM_DN1_MSG_TX_COUNT,
    DV_ELEM_DN1_MSG_RX_COUNT,
#else
    DV_ELEM_DN2_MSG_TX_COUNT,
    DV_ELEM_DN2_MSG_RX_COUNT,
#endif
};

NetworkManager::Config_t ProfilePlatform_Config::mCnNmConfig =
{
    // Nodes
    ProfilePlatform_Config::mNodes,
    // Channels
    ProfilePlatform_Config::mChannels,
    // Me
    NODE_CONTROL,
    // Msg Tx and Rx Counters.
    DV_ELEM_CN_MSG_TX_COUNT,
    DV_ELEM_CN_MSG_RX_COUNT,
};

/************************** COMMAND HANDLER CONFIG ****************************/

CommandHandler::Config_t ProfilePlatform_Config::mChConfig =
{
    DV_ELEM_CMD,
    DV_ELEM_CMD_REQ,
    DV_ELEM_CMD_WRITE_ELEM,
    DV_ELEM_CMD_WRITE_VAL,
    DV_ELEM_LAST_CMD_REQ_NUM,    
    DV_ELEM_LAST_CMD_PROC_NUM,
};
